update workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -60,13 +60,17 @@ jobs:
           projectKey: 'ab2d-events'
           serverUrl: 'https://sonarqube.cloud.cms.gov'
       
-      - name: Quality Gate
+      - name: Quality Gate Check
         if: github.event_name == 'pull_request'
-        uses: sonarsource/quality-gate-action@v2
+        run: |
+          status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=<your_project_key>" | jq -r .projectStatus.status)
+          echo $status
+          if [ "$status" != "OK" ]; then
+            echo "Quality Gate failed"
+            exit 1
+          fi
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        with:
-          waitForQualityGate: true
       
       - name: SBOM
         if: github.event_name == 'pull_request'
